apiVersion: developer.microsoft.com/v1
kind: Template
metadata:
  name: azure-search-openai-demo
  title: ChatGpt-like app with your data using Azure OpenAI and Azure AI Search (Python)
  description: |
    This template creates a github repo for Python app that uses Azure OpenAI and Azure AI Search to provide a ChatGpt-like experience with your data.
  namespace: contoso-inc
  provider: github.com
  labels:
    github.com/org: Azure-Samples
    github.com/name: azure-search-openai-demo
  links:
    - url: https://github.com/organizations/Contoso-Inc/repositories/new
      title: web
  tags:
    - github
    - repository
    - create
    - azd
spec:
  inputJsonSchema: "{\"type\":\"object\",\"properties\":{\"name\":{\"title\":\"name\",\"description\":\"The name of the repository\"},\"description\":{\"title\":\"description\",\"description\":\"description of the repo\",\"type\":\"string\"},\"visibility\":{\"title\":\"visibility\",\"description\":\"visibility of the repo\",\"type\":\"boolean\", \"default\":true},\"required\":[\"name\", \"description\"]}"
  creates:
    - kind: Repository
      namespace: contoso-inc
